/* automatically generated by pepy 8.0 #11 (tiber), do not edit! */

#include "psap.h"

#define	advise	PY_advise

void	advise ();

/* Generated from module UNIV */

#ifndef	lint
static char *rcsid = "$Header: /xtel/isode/isode/pepsy/RCS/UNIV.py,v 9.0 1992/06/16 12:24:03 isode Rel $";
#endif

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	parse_UNIV_GraphicString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p10;
    int p10_len;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.GraphicString");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 25)) {
        advise (NULLCP, "GraphicString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p10 = prim2str (pe, &p10_len)) == NULLCP) {
        advise (NULLCP, "GraphicString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p10_len;
    if (buffer)
        *buffer = p10;
    else
        if (p10)
            free (p10);

    return OK;
}
