/* automatically generated by pepy 8.0 #2 (pilsen), do not edit! */

#include "psap.h"

#define	advise	PY_advise

#ifndef MAC
void	advise ();
#else
void advise(...);
#endif /* MAC */

/* Generated from module UNIV */

#ifndef	lint
static char *rcsid = "$Header: /xtel/isode/isode/pepsy/RCS/UNIV.py,v 9.0 1992/06/16 12:24:03 isode Rel $";
#endif

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	build_UNIV_IA5String (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p0;
    int p0_len;

    p0 = buffer;
    if ((p0_len = len) == 0)
        p0_len = strlen (p0);
    if (p0 == NULLCP) {
        advise (NULLCP, "IA5String %s", PEPY_ERR_INIT_FAILED);
        return NOTOK;
    }
    if (((*pe) = str2prim (p0, p0_len, PE_CLASS_UNIV, 22)) == NULLPE) {
        advise (NULLCP, "IA5String: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.IA5String");
#endif


    return OK;
}
