/* automatically generated by pepy 8.0 #2 (pilsen), do not edit! */

#include "psap.h"

#define	advise	PY_advise

#ifndef MAC
void	advise ();
#else
void advise(...);
#endif /* MAC */

/* Generated from module UNIV */

#ifndef	lint
static char *rcsid = "$Header: /xtel/isode/isode/pepsy/RCS/UNIV.py,v 9.0 1992/06/16 12:24:03 isode Rel $";
#endif

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	parse_UNIV_VisibleString (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p13;
    int p13_len;

#ifdef DEBUG
    (void) testdebug (pe, "UNIV.VisibleString");
#endif

    if (explicit
            && PE_ID (pe -> pe_class, pe -> pe_id)
                    != PE_ID (PE_CLASS_UNIV, 26)) {
        advise (NULLCP, "VisibleString %s%s/0x%x", PEPY_ERR_BAD_CLASS,
                pe_classlist[pe -> pe_class], pe -> pe_id);
        return NOTOK;
    }
    if ((p13 = prim2str (pe, &p13_len)) == NULLCP) {
        advise (NULLCP, "VisibleString %s%s", PEPY_ERR_BAD_OCTET,
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p13_len;
    if (buffer)
        *buffer = p13;
    else
        if (p13)
            free (p13);

    return OK;
}
