#########################################################################
#                                                                       #
#  Projectname          :       STAPAC                                  #
#                                                                       #
#  Date                 :       November 1991                           #
#                                                                       #
#  Author               :       L. Eckstein                             #
#                                                                       #
#  Filename             :       Makefile                                #
#                                                                       #
#  Description          :       this makefile generates the t1-         #
#                               object                                  #
#                                                                       #
#  DFLAGS		:       -DTRACE -DDOS   for DOS			#
#  DFLAGS		:       -DTRACE -DSUN   for BSD			#
#  DFLAGS		:       -DTRACE -DSUN -DSYSV   for  System V    #
#                                                                       #
#########################################################################
#TRACE    =      TRACE

DSCA     =
DD         = ../

SPECIALS    =  -D$(SYSTEM)

OBJS       =  t1.o
 
all: $(LIBSECUDE)


trace:	; make "OPT=$(OPT) -DTRACE"




























