/* automatically generated by posy 8.0 #7 (tiber), do not edit! */

#ifndef	_module_IF_defined_
#define	_module_IF_defined_

#include "psap.h"
#include "UNIV-types.h"

#define	type_IF_AttributeType	OIDentifier
#define	type_IF_AttributeValue	PElement

#define RDNAME 10 
#define ATTRIBUTEVALUES 11

typedef struct type_IF_AttributeType    	AttrType;
typedef struct type_IF_AttributeValues  	AttrValues;
typedef struct type_IF_AttributeValueAssertion  AttributeValueAssertion;


struct type_IF_AttributeValueAssertion {
    struct type_IF_AttributeType *element_IF_0;

    struct type_IF_AttributeValue *element_IF_1;
};
int	free_IF_AttributeValueAssertion ();

struct type_IF_Name {
        struct type_IF_RelativeDistinguishedName *element_IF_2;

        struct type_IF_Name *next;
};
int	free_IF_Name ();

struct type_IF_RelativeDistinguishedName {
        struct type_IF_AttributeValueAssertion *member_IF_0;

        struct type_IF_RelativeDistinguishedName *next;
};
int	free_IF_RelativeDistinguishedName ();

struct type_IF_AttributeValues {
        struct type_IF_AttributeValue *member_IF_1;

        struct type_IF_AttributeValues *next;
};
int	free_IF_AttributeValues ();

struct type_IF_Attribute {
    struct type_IF_AttributeType *type;

    struct type_IF_AttributeValues *values;
};
int	free_IF_Attribute ();
#endif
