/* automatically generated by pepy 8.0 #2 (pilsen), do not edit! */

#include "psap.h"

#define	advise	PY_advise

void	advise ();

/* Generated from module UNIV */

#ifndef	lint
static char *rcsid = "$Header: /xtel/isode/isode/pepsy/RCS/UNIV.py,v 9.0 1992/06/16 12:24:03 isode Rel $";
#endif

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	build_UNIV_VisibleString (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p12;
    int p12_len;

    p12 = buffer;
    if ((p12_len = len) == 0)
        p12_len = strlen (p12);
    if (p12 == NULLCP) {
        advise (NULLCP, "VisibleString %s", PEPY_ERR_INIT_FAILED);
        return NOTOK;
    }
    if (((*pe) = str2prim (p12, p12_len, PE_CLASS_UNIV, 26)) == NULLPE) {
        advise (NULLCP, "VisibleString: %s", PEPY_ERR_NOMEM);
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.VisibleString");
#endif


    return OK;
}
