#
#  SecuDE Release 4.1 (GMD)
#
#
#    Copyright (C) 1991, GMD Darmstadt
#
#                         NOTICE
#
#    Acquisition, use, and distribution of this module 
#    and related materials are subject to restrictions 
#    mentioned in each volume of the documentation.
#

DAFDB =

OBJS    =       pem_init.o pem_create.o pem_scan.o pem_rw.o

all: $(LIBSECUDE)
